FROM rustlang/rust:nightly-slim

# Install system dependencies for WebRTC, SQLx and OpenSSL
RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    libpq-dev \
    clang \
    git \
    python3 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

# The context is the root of the project
CMD ["cargo", "run", "--manifest-path", "services/sfu/Cargo.toml", "--release"]
