version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drmp
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  sfu:
    build:
      context: .
      dockerfile: services/sfu/Dockerfile.dev
    network_mode: host # LA SOLUTION ULTIME POUR LE WEBRTC
    environment:
      - DATABASE_URL=postgres://postgres:password@localhost:5433/drmp
      - RUST_LOG=info
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
